version:  '3.8'


services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - '3306'
    ports:
      - '9999:3306'
    volumes:
    - database-volume:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './apps/bedrock:/usr/src/app'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/bedrock:/usr/src/app'
    restart: on-failure
    env_file:
      - apps/bedrock/.env
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: ${MYSQL_CONTAINER_NAME}
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
      WP_DEBUG_LOG: ${WP_DEBUG_LOG}
    user: ${LOCAL_USER}

volumes:
  database-volume:
